from elasticsearch import Elasticsearch
from datetime import datetime
import pandas as pd
import os
import json
import random
from tqdm import tqdm
# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "r3EVROJidon4TdOeNget2aRK"

# Found in the 'Manage Deployment' page
CLOUD_ID = "InferIA_prototipo_10:ZXVyb3BlLXdlc3QzLmdjcC5jbG91ZC5lcy5pbyQxNzQwMjk4OTc5OWY0MTIwYmIyZjk3OWI1NGIzNDU3ZCQwNGU2YTg2NjA4YmQ0YjQzOTc5ODBlYTdkYTNmMTYwOQ=="

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())

files = os.listdir("./data/datos.gob.es") # all files in data
for file in tqdm(files):
    if file[:5]== 'meta_':

        with open("./data/datos.gob.es/" + file, 'r') as f:
            data = json.load(f)
            
        doc = {
            'title': data['title'],
            'description': data['description'],
            'theme': data['theme'],
            'modified': data['modified'],
            'license' : data['license'],
            'provider': 'Datos.gob.es',
            'resources': data['resources']
        }

        resp = client.index(index="search-test", id=random.randint(0,999999), document=doc)