from elasticsearch import Elasticsearch
from fastapi.middleware.cors import CORSMiddleware
from fastapi import FastAPI

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "r3EVROJidon4TdOeNget2aRK"

# Found in the 'Manage Deployment' page
CLOUD_ID = "InferIA_prototipo_10:ZXVyb3BlLXdlc3QzLmdjcC5jbG91ZC5lcy5pbyQxNzQwMjk4OTc5OWY0MTIwYmIyZjk3OWI1NGIzNDU3ZCQwNGU2YTg2NjA4YmQ0YjQzOTc5ODBlYTdkYTNmMTYwOQ=="

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

app = FastAPI()

origins = ["*"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/search")
async def search(keywords:str):

    resp = client.search(index="search-test", size=1000, query={"match": {"title": {"query": keywords}}})

    result = []
    total = resp['hits']['total']['value']

    for hit in resp['hits']['hits']:
        data = hit['_source']

        result.append(data)

    return {"results": result, "total": total}